/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.uaa.vista;

import com.uaa.controlador.MemData;
import com.uaa.modelo.ConexionBD;
import com.uaa.modelo.Hotel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel
 */
public class ABMHoteles extends javax.swing.JInternalFrame {

    /**
     * Creates new form ABMHoteles
     */
    public ABMHoteles() {
        initComponents();
        initComboBox();
        listar();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        paneldatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboTipoHotel = new javax.swing.JComboBox<>();
        buttonAgregar = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        comboPais = new javax.swing.JComboBox<>();
        txtCiudad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("ABM Hoteles");
        jLabel1.setName(""); // NOI18N

        paneldatos.setBackground(new java.awt.Color(0, 0, 204));

        jLabel2.setText("Datos");

        jLabel3.setText("ID:");

        jLabel4.setText("Tipo Hotel:");

        jLabel5.setText("Codigo Postal:");

        jLabel6.setText("Nombre:");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        jLabel7.setText("Dirección:");

        jLabel8.setText("Pais:");

        comboTipoHotel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Playa", "Naturaleza", "Ciudad" }));

        buttonAgregar.setText("AGREGAR");
        buttonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarActionPerformed(evt);
            }
        });

        buttonModificar.setText("MODIFICAR");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        buttonEliminar.setText("ELIMINAR");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Codigo Postal", "Tipo Hotel", "Nombre", "Direccion", "Pais", "Ciudad"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jLabel9.setText("Ciudad:");

        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneldatosLayout = new javax.swing.GroupLayout(paneldatos);
        paneldatos.setLayout(paneldatosLayout);
        paneldatosLayout.setHorizontalGroup(
            paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldatosLayout.createSequentialGroup()
                .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneldatosLayout.createSequentialGroup()
                            .addGap(143, 143, 143)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonAgregar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonModificar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonEliminar))
                        .addGroup(paneldatosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel9))))
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCiudad)
                    .addComponent(txtDireccion)
                    .addComponent(txtId)
                    .addComponent(txtCod)
                    .addComponent(txtNombre)
                    .addComponent(comboTipoHotel, 0, 378, Short.MAX_VALUE)
                    .addComponent(comboPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        paneldatosLayout.setVerticalGroup(
            paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneldatosLayout.createSequentialGroup()
                        .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipoHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(paneldatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAgregar)
                    .addComponent(buttonModificar)
                    .addComponent(buttonEliminar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(paneldatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneldatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void buttonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarActionPerformed
        Hotel hot=new Hotel();
        
        hot.setIdHotel(Integer.parseInt(txtId.getText()));
       
        if (comboTipoHotel.getSelectedItem().toString().equals("Playa")){
            hot.setTipoHotel(0);

}
        else if(comboTipoHotel.getSelectedItem().toString().equals("Ciudad")){
            hot.setTipoHotel(2);}
         else{
            hot.setTipoHotel(3);
   }
       

        hot.setCodPostal(Integer.parseInt(txtCod.getText()));
        hot.setNombre(txtNombre.getText());
        if(comboPais.getSelectedItem().equals(MemData.lstPaises[0])){
            hot.setPais(0);
        }
        else if(comboPais.getSelectedItem().equals(MemData.lstPaises[1])){
            hot.setPais(1);
        }
        else if(comboPais.getSelectedItem().equals(MemData.lstPaises[2])){
            hot.setPais(2);
        }
        else if(comboPais.getSelectedItem().equals(MemData.lstPaises[3])){
            hot.setPais(3);
        }
        else if(comboPais.getSelectedItem().equals(MemData.lstPaises[4])){
            hot.setPais(4);
        }
        else{
            hot.setPais(5);
        }
        hot.setCiudad(txtCiudad.getText());
      
        
        hot.grabar();
        limpiarDatos();
        listar();
        JOptionPane.showMessageDialog(null, "Hotel Agregado");
        
    }//GEN-LAST:event_buttonAgregarActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
       modificar();
       listar();
       limpiarDatos();
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
      eliminar();
      listar();
      limpiarDatos();
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
         int fila=jTable2.getSelectedRow();
      if(fila==-1){
          JOptionPane.showMessageDialog(null, "Usuario no seleccionado");
                  }else{
                    int Id=Integer.parseInt((String)jTable2.getValueAt(fila, 0).toString());
                    int tipohot=Integer.parseInt((String)jTable2.getValueAt(fila, 2).toString());
                    int codpost=Integer.parseInt((String)jTable2.getValueAt(fila, 1).toString());
                    String nombre=(String)jTable2.getValueAt(fila, 3);
                    String direccion=(String)jTable2.getValueAt(fila, 4);
                    int pais=Integer.parseInt((String)jTable2.getValueAt(fila, 5).toString());
                    String ciudad=(String)jTable2.getValueAt(fila, 6);
                    
                    txtCiudad.setText(""+ciudad);
                    comboPais.getModel().setSelectedItem(""+pais);
                    comboTipoHotel.getModel().setSelectedItem(""+tipohot);
                    txtCod.setText(""+codpost);
                    txtDireccion.setText(direccion);
                    txtNombre.setText(nombre);
                    txtId.setText("" + Id);
          
      }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Cerrando...");
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
   private void limpiarDatos(){
        txtCiudad.setText("");
        comboPais.getModel().setSelectedItem("Uruguay");
        comboTipoHotel.getModel().setSelectedItem("Playa");
        txtCod.setText("");
        txtDireccion.setText("");
        txtNombre.setText("");
        txtId.setText("");
    }
   
 private void initComboBox() {
        for (String pais : MemData.lstPaises) {
            comboPais.addItem(pais);
        }

 }
  void listar() {
    Hotel pes=new Hotel();

         DefaultTableModel tblModel = (DefaultTableModel)jTable2.getModel();
        Object rowData[] = new Object[7];
        ArrayList<Hotel> lstHoteles = pes.getHoteles();

        tblModel.setRowCount(0);
        for (int i=0; i<lstHoteles.size(); i++) {
       
                rowData[0] = lstHoteles.get(i).getIdHotel();
                rowData[1] = lstHoteles.get(i).getCodPostal();
                rowData[2] = MemData.tipoHoteles[lstHoteles.get(i).getTipoHotel()];
                rowData[3] = lstHoteles.get(i).getNombre();
                rowData[4] = lstHoteles.get(i).getDireccion();
                rowData[5] = MemData.lstPaises[lstHoteles.get(i).getPais()];
                rowData[6] = lstHoteles.get(i).getCiudad();
                

                tblModel.addRow(rowData);
            
        }  
        
    }
  void eliminar(){
       int fila = jTable2.getSelectedRow();
         int columna= 0;
         int idEliminado = Integer.parseInt(jTable2.getModel().getValueAt(fila, columna).toString());
         System.out.println(idEliminado);
         
        if (fila < 0) {
            JOptionPane.showMessageDialog(null,"Usuario no Seleccionado");
        } else try{
            String myDriver = "com.mysql.cj.jdbc.Driver";
            
            Class.forName(myDriver);
            String query = "delete from pasajeros where idHotel="+idEliminado;
            ConexionBD c = new ConexionBD();
            String myUrl = c.getUrl() + c.getServerName() + "/" + c.getDatabaseName()+"?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false";
            Connection cn = DriverManager.getConnection(myUrl, c.getUserName(), c.getPassword());
            PreparedStatement cmd = cn.prepareStatement(query);
            cmd.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Usuario Eliminado");
            
        }
        catch(Exception e){
            System.out.println(e);
        }
    
}
  void modificar(){
      int id=Integer.parseInt(txtId.getText());
      int tipohotel;
      if(comboTipoHotel.getSelectedItem().toString().equals("Naturaleza")){
          tipohotel=0;
      }
      else if(comboTipoHotel.getSelectedItem().toString().equals("Playa")){
      tipohotel=1;
  }
      else{
          tipohotel=2;
      }
      String codpostal=txtCod.getText();
      String direccion=txtDireccion.getText();
      String nombre=txtNombre.getText();
      int pais=Integer.parseInt(comboPais.getSelectedItem().toString());
      String ciudad=txtCiudad.getText();
       try{ 
            String myDriver = "com.mysql.cj.jdbc.Driver";
            
            Class.forName(myDriver);
            
            ConexionBD c = new ConexionBD();
            String myUrl = c.getUrl() + c.getServerName() + "/" + c.getDatabaseName()+"?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false";
            Connection cn = DriverManager.getConnection(myUrl, c.getUserName(), c.getPassword());
            String query = "update pasajeros set codPostal = ?, tipoHotel = ?, nombre = ?, direccion = ?, pais = ?, ciudad = ? where idPasajero = ?";
            PreparedStatement cmd = cn.prepareStatement(query);
            cmd.setString(1, codpostal);
            cmd.setInt(2, tipohotel);
            cmd.setString(3, nombre);
            cmd.setString(4, direccion);
            cmd.setInt(5, pais);
            cmd.setString(6, ciudad);
            cmd.setInt(7, Integer.parseInt(txtId.getText()));
            cmd.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Usuario Actualizado");
        }catch(Exception e){System.out.println(e);}
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JComboBox<String> comboPais;
    private javax.swing.JComboBox<String> comboTipoHotel;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable2;
    private javax.swing.JPanel paneldatos;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
