/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uaa.vista;

import com.uaa.controlador.MemData;
import com.uaa.modelo.ConexionBD;
import com.uaa.modelo.Hospedaje;
import com.uaa.modelo.Lavanderia;
import com.uaa.modelo.Pasajero;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class Facturacion extends javax.swing.JFrame {

    /**
     * Creates new form Facturacion
     */
    public Facturacion() {
        initComponents();
        initPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comId = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comHabitacion = new javax.swing.JComboBox<>();
        txtPrecioHabitacion = new javax.swing.JTextField();
        txtPrecioLavanderia = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        buttonFactura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setText("Facturacion");

        jLabel2.setText("ID Pasajero");

        comId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comIdActionPerformed(evt);
            }
        });

        jLabel3.setText("Número Habitación:");

        comHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comHabitacionActionPerformed(evt);
            }
        });

        buttonFactura.setText("FACTURAR");
        buttonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacturaActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio Habitación:");

        jLabel5.setText("Precio Lavandería:");

        jLabel6.setText("Precio Total:");

        jLabel7.setText("Estado: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonFactura)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))
                                            .addGap(24, 24, 24))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotal)
                                    .addComponent(txtPrecioLavanderia)
                                    .addComponent(txtPrecioHabitacion)
                                    .addComponent(comId, 0, 416, Short.MAX_VALUE)
                                    .addComponent(comHabitacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEstado))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioLavanderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(buttonFactura)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacturaActionPerformed
        int estado = 0;

        if (txtEstado.getText().equals("En Espera")) {
            txtEstado.setText("Pagado");
            estado = 0;
            JOptionPane.showMessageDialog(null, "La factura ha sido procesada");
        }
        else {       
            estado = 1;
            JOptionPane.showMessageDialog(null, "La factura ya ha sido procesada anteriormente");
        }      
        
        Hospedaje hos = new Hospedaje();
        if (estado==0) {
            for (Hospedaje h : hos.getHospedajes()) {
                if (h.getHabitacion().getNroHabitacion()==Integer.parseInt(comHabitacion.getSelectedItem().toString())) {
                    h.setEstado(1); 
                    
                    estado = 1;
                    
                    try{ 
                        String myDriver = "com.mysql.cj.jdbc.Driver";

                        Class.forName(myDriver);

                        ConexionBD c = new ConexionBD();
                        String myUrl = c.getUrl() + c.getServerName() + "/" + c.getDatabaseName()+"?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false";
                        Connection cn = DriverManager.getConnection(myUrl, c.getUserName(), c.getPassword());

                        int id = Integer.parseInt(comId.getSelectedItem().toString());

                        String query = "update hospedajes set estado = ? where idPasajero = ?";
                        PreparedStatement cmd = cn.prepareStatement(query);
                        cmd.setInt(1,estado);
                        cmd.setInt(2, id);

                        cmd.executeUpdate();

                    }catch(Exception e){System.out.println(e);}                                  
                }
            }          
        }
        
        
    }//GEN-LAST:event_buttonFacturaActionPerformed

    private void comIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comIdActionPerformed
        comHabitacion.removeAllItems();
        Hospedaje hos = new Hospedaje();
        

        if (comId.getSelectedItem()!=null) {
            for (Hospedaje ho : hos.getHospedajes()) {
                if (ho.getPasajero().getIdPasajero()==Integer.parseInt(comId.getSelectedItem().toString())) {
                    comHabitacion.addItem(String.valueOf(ho.getHabitacion().getNroHabitacion()));
                    txtEstado.setText(MemData.estados[ho.getEstado()]);
                } 
                
            }            
        }

        
 
    }//GEN-LAST:event_comIdActionPerformed

    private void comHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comHabitacionActionPerformed
        if (comHabitacion.getSelectedItem()!=null) {
            Hospedaje hos = new Hospedaje();
            Lavanderia lav = new Lavanderia();
            
            int precioHab = 0;
            int precioLav = 0;
            int precioTotal = 0;
            
            for (Hospedaje ho : hos.getHospedajes()) {
                if (ho.getPasajero().getIdPasajero()==Integer.parseInt(comId.getSelectedItem().toString())) {
                    precioHab = ho.getHabitacion().getPrecio();
                    txtPrecioHabitacion.setText(String.valueOf(precioHab));
                } 
                boolean ban = false;
                for (Lavanderia l : lav.getServicios()) {
                    if (l.getHabitacion().getNroHabitacion()==Integer.parseInt(comHabitacion.getSelectedItem().toString())) {
                        precioLav = l.getCantidad()*l.precioUnitario;
                        txtPrecioLavanderia.setText(String.valueOf(precioLav));
                        ban = true;
                    }
                }
                if (ban==false) {
                    txtPrecioLavanderia.setText("0");
                }
                precioTotal = precioHab+precioLav;
                txtTotal.setText(String.valueOf(precioTotal));
            }   
        }
    }//GEN-LAST:event_comHabitacionActionPerformed
private void initPantalla() {
        txtPrecioHabitacion.setEditable(false);
        txtPrecioLavanderia.setEditable(false);
        txtTotal.setEditable(false);
        
        Pasajero pas = new Pasajero();
        for(Pasajero p : pas.getPasajeros()){
            comId.addItem(String.valueOf(p.getIdPasajero()));
        }
        
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFactura;
    private javax.swing.JComboBox<String> comHabitacion;
    private javax.swing.JComboBox<String> comId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtPrecioHabitacion;
    private javax.swing.JTextField txtPrecioLavanderia;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
