/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uaa.vista;

import com.uaa.modelo.Hotel;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import com.uaa.controlador.MemData;

/**
 *
 * @author ub3721
 */
public class ListaHotelesConsorcio extends javax.swing.JFrame {

    /**
     * Creates new form LIstaHotelesConsorcio
     */
    public ListaHotelesConsorcio() {
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdListaConsorcio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Hoteles del Consorcio");

        grdListaConsorcio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Hotel", "Cod. Postal", "Tipo Hotel", "Nombre", "Direccion", "Pais", "Ciudad"
            }
        ));
        grdListaConsorcio.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(grdListaConsorcio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaHotelesConsorcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaHotelesConsorcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaHotelesConsorcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaHotelesConsorcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaHotelesConsorcio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grdListaConsorcio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        DefaultTableModel tblModel = (DefaultTableModel) grdListaConsorcio.getModel();
        Object rowData[] = new Object[12];
        
        /*Hotel h1 = new Hotel(1,21,1,"Hotel nombre", "En la esquina", 2, "Asuncion");
        h1.grabar();
        
        Hotel h2 = new Hotel(2,24,2,"Hotel 2", "En la rotonda", 4, "La paz");
        h2.grabar();   */   
        
        
        Hotel hotel = new Hotel();
        ArrayList<Hotel> lstHoteles = hotel.getHoteles();
        
        
        for (int i=0; i<lstHoteles.size(); i++) {
            rowData[0] = lstHoteles.get(i).getIdHotel();
            rowData[1] = lstHoteles.get(i).getCodPostal();
            rowData[2] = MemData.tipoHoteles[lstHoteles.get(i).getTipoHotel()];
            rowData[3] = lstHoteles.get(i).getNombre();
            rowData[4] = lstHoteles.get(i).getDireccion();
            rowData[5] = MemData.lstPaises[lstHoteles.get(i).getPais()];
            rowData[6] = lstHoteles.get(i).getCiudad();
            
            tblModel.addRow(rowData);
        }    
    }
}
